# Discovery Server Access
eureka:
  instance:
    hostname: cart-microservice
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://discovery-microservice:8001/eureka/

# HTTP (Tomcat) server port
server:
  port: 9002
