spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/venkataravuri/config-repo

eureka:
  instance:
    hostname: configuration-microservice
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://discovery-microservice:8001/eureka/